import { generateHardwareVector } from './src/lib/fingerprint.js';
import crypto from 'node:crypto';
globalThis.window = globalThis;
Object.defineProperty(globalThis, 'crypto', { value: crypto.webcrypto || crypto });
Object.defineProperty(globalThis, 'navigator', { value: { userAgent: 'test' } });
globalThis.screen = { width: 1920, height: 1080 };
globalThis.document = { createElement: () => ({ toDataURL: () => 'mock', getContext: () => ({ getExtension: () => ({ UNMASKED_RENDERER_WEBGL: 1 }), getParameter: () => 'test' }) }) };
globalThis.AudioContext = class { close(){} };
globalThis.OfflineAudioContext = class { constructor(){} createOscillator(){ return { type: '', frequency: {}, connect(){}, start(){} } } createDynamicsCompressor(){ return { threshold: {}, knee:{}, ratio:{}, reduction:{}, attack:{}, release:{}, connect(){} } } get destination(){ return {} } startRendering(){ return Promise.resolve({ getChannelData: () => new Float32Array(10) }) } };
generateHardwareVector().then(console.log).catch(console.error);
